export const dashboardNavLinks = [
    { label: "Profile", href: "/profile", icon: "User" },
    { label: "Cart", href: "/Cart", icon: "ShoppingBag" },
    { label: "Settings", href: "/settings", icon: "Settings" },
    { label: "Tests", href: "/EducationTest", icon: "ScrollText" },
    { label: "Kundlis", href: "/KundliCloud", icon: "Layers" },
    { label: "Saved Papers", href: "/SavedPaper", icon: "BookMarked" },
];
export const userProfile = {
    id: "astro_user_001",
    name: "Aarav Desai",
    email: "aarav@kalyan.ai",
    location: "Bangalore, India",
    timezone: "IST (+05:30)",
    zodiac: "Pisces ☽",
    kundliBadge: "Crystal Vision",
    avatar: "/placeholder-user.jpg",
    memberSince: "March 2024",
    bio: "Founder at VedaLab • Exploring AI-assisted Jyotish to craft calmer routines and mindful rituals.",
};
export const profileStats = [
    {
        label: "Saved Charts",
        value: "28",
        helper: "4 new this week",
        trend: "+14%",
    },
    {
        label: "Tests Completed",
        value: "12",
        helper: "Last score 92%",
        trend: "+2%",
    },
    {
        label: "Purchases",
        value: "9",
        helper: "Next delivery in 3 days",
        trend: "+6%",
    },
];
export const kundliHistory = [
    {
        id: "kundli_001",
        title: "Raj & Meera Compatibility",
        chartType: "D9 • Navamsa",
        generatedAt: "Nov 22, 2025 — 08:42",
        feeling: "Harmony: 86%",
        status: "ready",
    },
    {
        id: "kundli_002",
        title: "Aarav Personal Chart",
        chartType: "D1 • Lagna",
        generatedAt: "Nov 19, 2025 — 21:10",
        feeling: "Momentum: High",
        status: "ready",
    },
    {
        id: "kundli_003",
        title: "Career Transit",
        chartType: "Transit Overlay",
        generatedAt: "Nov 17, 2025 — 05:16",
        feeling: "Focus: Deep",
        status: "processing",
    },
];
export const cartItems = [
    {
        id: "poster_d9",
        name: "Custom D9 Cosmic Poster",
        description: "Archival matte print, silver foil zodiac ring",
        category: "Poster",
        deliveryEstimate: "Ships in 48h",
        thumbnail: "/Poster/Bento/D9-Poster.webp",
        price: 129,
        quantity: 1,
        accent: "from-indigo-200/80 to-indigo-100/20",
    },
    {
        id: "perfume_calm",
        name: "Calm Aura Perfume",
        description: "Lavender • Mysore sandalwood • Neroli",
        category: "Perfume",
        deliveryEstimate: "Arrives Dec 02",
        thumbnail: "/Perfume/perfume-03.png",
        price: 89,
        quantity: 2,
        accent: "from-rose-100/80 to-rose-50/40",
    },
    {
        id: "gem_moonstone",
        name: "Moonstone Meditation Bracelet",
        description: "Ethically sourced Sri Lankan moonstone",
        category: "Gem",
        deliveryEstimate: "Appraised & ready",
        thumbnail: "/Gems/Moonstone.webp",
        price: 210,
        quantity: 1,
        accent: "from-blue-100/80 to-blue-50/40",
    },
];
export const availableTests = [
    {
        id: "vedic_basics",
        title: "Vedic Intelligence Baseline",
        duration: "12 min",
        status: "completed",
        score: 92,
        focus: "Elemental balance • D1 insights",
    },
    {
        id: "karma_routes",
        title: "Karma Route Mapping",
        duration: "8 min",
        status: "in-progress",
        score: 64,
        focus: "Dasha transitions • Remedial focus",
    },
    {
        id: "synastry_lite",
        title: "Synastry Lite",
        duration: "10 min",
        status: "not-started",
        focus: "Navamsa overlays • Compatibility pulse",
    },
];
export const kundliCards = [
    {
        id: "lagna_signature",
        title: "Core Signature",
        chart: "D1 Lagna",
        layer: "Life Path",
        updatedAt: "2h ago",
        energy: "Steady",
        filter: "D1",
    },
    {
        id: "navamsa_story",
        title: "Relationship Narrative",
        chart: "D9 Navamsa",
        layer: "Sacred Bonding",
        updatedAt: "Yesterday",
        energy: "Magnetic",
        filter: "D9",
    },
    {
        id: "career_field",
        title: "Career Momentum",
        chart: "D10 Dasamsa",
        layer: "Mastery",
        updatedAt: "4 days ago",
        energy: "Rising",
        filter: "D10",
    },
    {
        id: "soul_depth",
        title: "Soul Memory",
        chart: "D12 Dwadashamsa",
        layer: "Lineage",
        updatedAt: "1 week ago",
        energy: "Deep Tide",
        filter: "D12",
    },
    {
        id: "custom_overlay",
        title: "Transit Overlay",
        chart: "Custom Blend",
        layer: "Now",
        updatedAt: "Live",
        energy: "Charged",
        filter: "Custom",
    },
];
export const kundliFilters = ["All", "D1", "D9", "D10", "D12", "Custom"];
export const savedPapers = [
    {
        id: "paper_01",
        title: "Moon Mahadasha Emotional Matrix",
        type: "Research",
        tags: ["PDF", "Dasha"],
        updatedAt: "Nov 11, 2025",
        preview: "Layered journal exploring lunar cycles and heart coherence practices during the Moon Mahadasha.",
        downloadUrl: "/Research-Paper/Jyotish.pdf",
    },
    {
        id: "paper_02",
        title: "Astro Cognitive Test — 2025",
        type: "Assessment",
        tags: ["Assessment", "AI"],
        updatedAt: "Nov 05, 2025",
        preview: "Adaptive AI-driven test summarizing intuition, recall, and synthesis scores mapped to divisional charts.",
        downloadUrl: "/Research-Paper/Jyotish.pdf",
    },
    {
        id: "paper_03",
        title: "Navamsa Ritual Notes",
        type: "Notes",
        tags: ["Navamsa", "Daily"],
        updatedAt: "Oct 29, 2025",
        preview: "Minimal rituals documented through D9 overlays to sustain softness in relational energy.",
        downloadUrl: "/Research-Paper/Jyotish.pdf",
    },
];
